#line 2 "babs_lexer.c"

#line 4 "babs_lexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer babs_create_buffer
#define yy_delete_buffer babs_delete_buffer
#define yy_flex_debug babs_flex_debug
#define yy_init_buffer babs_init_buffer
#define yy_flush_buffer babs_flush_buffer
#define yy_load_buffer_state babs_load_buffer_state
#define yy_switch_to_buffer babs_switch_to_buffer
#define yyin babsin
#define yyleng babsleng
#define yylex babslex
#define yylineno babslineno
#define yyout babsout
#define yyrestart babsrestart
#define yytext babstext
#define yywrap babswrap
#define yyalloc babsalloc
#define yyrealloc babsrealloc
#define yyfree babsfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE babsrestart(babsin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int babsleng;

extern FILE *babsin, *babsout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up babstext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up babstext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via babsrestart()), so that the user can continue scanning by
	 * just pointing babsin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when babstext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int babsleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow babswrap()'s to do buffer switches
 * instead of setting up a fresh babsin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void babsrestart (FILE *input_file  );
void babs_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE babs_create_buffer (FILE *file,int size  );
void babs_delete_buffer (YY_BUFFER_STATE b  );
void babs_flush_buffer (YY_BUFFER_STATE b  );
void babspush_buffer_state (YY_BUFFER_STATE new_buffer  );
void babspop_buffer_state (void );

static void babsensure_buffer_stack (void );
static void babs_load_buffer_state (void );
static void babs_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER babs_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE babs_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE babs_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE babs_scan_bytes (yyconst char *bytes,int len  );

void *babsalloc (yy_size_t  );
void *babsrealloc (void *,yy_size_t  );
void babsfree (void *  );

#define yy_new_buffer babs_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        babsensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            babs_create_buffer(babsin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        babsensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            babs_create_buffer(babsin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *babsin = (FILE *) 0, *babsout = (FILE *) 0;

typedef int yy_state_type;

extern int babslineno;

int babslineno = 1;

extern char *babstext;
#define yytext_ptr babstext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up babstext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	babsleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 64
#define YY_END_OF_BUFFER 65
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[577] =
    {   0,
        0,    0,   65,   64,   63,   64,   62,   61,   55,   54,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   63,   60,   62,   62,    0,   61,
       62,   62,   62,   62,   62,   62,   62,   62,   57,   62,
       62,   62,   62,   62,   62,    0,    0,    1,   62,   59,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   56,   58,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,    0,   62,
       62,   62,   62,   62,    0,   62,   62,   62,   62,   62,

       62,    0,   62,    0,   62,   62,    0,   62,   62,   62,
        0,   62,   62,    0,    0,   62,   62,   62,   62,   62,
       62,   62,    0,    0,    0,    0,    0,   62,   62,   62,
       62,   62,    0,    0,    0,   62,   62,   62,   62,    0,
       62,   62,   62,    0,    0,    0,    0,   62,   62,   62,
       62,   62,    0,    0,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,    0,   62,    0,    0,    0,
        0,    0,    0,   21,    0,   62,   62,   62,   62,   62,
       62,   21,   62,    0,    0,    0,   62,   62,   62,   62,
        0,   62,   47,   45,    0,    0,    0,    0,   62,   62,

       62,   62,    0,   62,    0,    0,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,    0,    0,
        0,    0,    0,   62,   62,   62,   62,   62,    0,    0,
        0,    0,    0,    0,    0,   62,   62,   62,   62,   62,
       62,   62,    0,    0,    0,   62,   62,   62,   62,    0,
       62,    0,    0,    0,    0,   62,   62,   62,   62,    0,
        0,    0,    0,    0,   62,   62,   62,   62,   62,    0,
        0,    0,   62,   62,   62,   46,   62,   62,   62,   62,
       62,   62,   62,   62,   62,    0,    0,    0,    0,    0,
        0,   13,    0,   62,   62,   62,   62,   62,   62,   13,

       62,   20,    0,    0,   24,    0,   25,   18,   20,   62,
       62,   24,   62,   25,   18,    0,   50,    0,   62,   50,
       62,    0,   62,    0,   62,    0,    0,   28,    0,   62,
       62,   28,   62,    0,    0,    0,    0,    0,    0,   35,
        0,   62,   62,   62,   62,   62,   62,   35,   62,    0,
        0,    0,   62,   62,   62,   62,   62,    4,   62,    6,
       62,   62,   62,   62,    0,    0,    0,    0,    0,    0,
        0,   62,   62,   62,   62,   62,   62,   62,    0,    0,
        0,   62,   62,   62,   48,    0,   48,   62,    0,   62,
       51,   51,    0,    0,    0,   62,   62,   62,    0,    0,

        0,    0,    0,    0,    0,   62,   62,   62,   62,   62,
       62,   62,    0,    0,    0,   62,   62,   62,   62,   62,
       62,   62,   62,   62,    5,   62,   62,   12,    0,    0,
       16,    0,   17,   10,   12,   62,   62,   16,   62,   17,
       10,   19,    0,   22,   19,   62,   22,    0,   62,    0,
       62,    0,    0,   29,   62,   62,   29,   36,    0,    0,
       39,    0,   40,   33,   36,   62,   62,   39,   62,   40,
       33,    0,   42,    0,   62,   42,   62,   62,   62,   62,
       62,    2,   62,    9,   62,   62,    0,    0,    0,   62,
       62,   62,    0,   62,   49,   49,    0,   62,    0,   27,

       62,   27,    0,    0,    0,   62,   62,   62,    0,    0,
       62,   62,   62,   62,   62,   62,   62,    8,    3,   11,
        0,   14,   11,   62,   14,   23,   23,    0,   62,    0,
       62,   34,    0,   37,   34,   62,   37,    0,   44,   62,
       44,   62,   62,   62,   62,   62,    0,   62,    0,   62,
       26,   26,    0,   62,   43,   43,   52,   62,   30,   62,
       62,   15,   15,   41,   41,   38,   38,   62,   62,    7,
       53,   31,   62,   62,   32,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    4,    5,    6,    7,    8,    7,
        7,    7,    7,    7,    7,    7,    7,    1,    9,    1,
       10,    1,    1,    1,   11,   12,   13,   14,   15,   16,
       17,   18,   19,   17,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   17,   17,   17,
        1,    1,    1,    1,   33,    1,   34,   35,   36,   37,

       38,   39,   40,   41,   42,   17,   17,   43,   44,   45,
       46,   47,   48,   49,   50,   51,   52,   53,   54,   55,
       56,   57,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[58] =
    {   0,
        1,    1,    2,    1,    3,    3,    3,    3,    1,    1,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3
    } ;

static yyconst flex_int16_t yy_base[588] =
    {   0,
        0,    0,  681,  682,   56,   53,  674,   57,  682,  682,
        0,  668,  659,  647,  665,  626,  622,  635,  630,   17,
      622,  618,   28,  631,   67,   66,    0,   74,   73,   80,
      656,  655,  651,  642,  615,  614,   47,  627,    0,  620,
      614,  621,  609,  611,  606,   82,  652,  682,   94,   84,
      626,  620,  622,  637,  608,  599,  596,  613,  596,  596,
      593,  591,  589,  594,    0,   92,  607,  612,  623,  613,
      583,  584,  594,  584,  104,  594,  585,  592,  587,  108,
      602,  616,  593,  603,  590,  118,  122,  572,  573,  572,
      586,  583,  132,  582,   63,   77,  587,  593,  603,  581,

      570,   96,  105,  112,  115,  560,  577,  576,  572,  562,
      108,  117,  569,  572,  553,  570,  551,  587,  587,  570,
      154,  171,  550,  117,  560,  148,  118,  548,  149,  558,
      152,  141,  546,  549,  559,  543,  546,  556,  540,  543,
      542,  536,  542,  550,  545,  526,  539,  546,  541,  522,
      535,  189,  521,  537,  519,  535,  542,  547,  543,  550,
      181,  544,  538,  542,  542,  157,  166,  518,  519,  528,
      527,  507,  521,  682,  511,  511,  512,  521,  520,  500,
      514,    0,  504,  501,  510,  499,  498,  507,  496,  506,
      506,  505,    0,    0,  486,  491,  492,  493,  482,  487,

      488,  489,  175,  184,  109,  481,  160,  480,  516,  508,
      501,  507,  500,  501,  498,  506,  504,  503,  472,  178,
      482,  195,  174,  470,  187,  480,  202,  185,  473,  481,
      478,  469,  475,  459,  473,  466,  474,  471,  462,  468,
      452,  466,  457,  456,  456,  454,  453,  453,  236,  451,
      450,  452,  441,  455,  455,  448,  437,  451,  451,  438,
      208,  448,  210,  197,  436,  214,  446,  215,  205,  434,
      440,  443,  431,  437,  440,    0,  444,  447,  460,  454,
      448,  450,  456,  442,  453,  422,  423,  432,  431,  411,
      425,  682,  415,  415,  416,  425,  424,  404,  418,    0,

      408,  682,  417,  414,  682,  401,  682,  682,    0,  414,
      411,    0,  398,    0,    0,  399,  682,  405,  397,    0,
      403,  394,  393,  398,  397,  402,  401,  682,  392,  399,
      398,    0,  389,  388,  389,  398,  397,  377,  391,  682,
      381,  381,  382,  391,  390,  370,  384,    0,  374,  371,
      375,  361,  368,  372,  358,   74,  381,    0,  389,  379,
      400,  383,  381,  384,  363,  371,  368,  359,  365,  349,
      363,  356,  364,  361,  352,  358,  342,  356,  359,  343,
      345,  356,  340,  342,  682,  342,    0,  341,  351,  350,
      682,    0,  338,  333,  327,  335,  330,  324,  333,  341,

      338,  329,  335,  319,  333,  326,  334,  331,  322,  328,
      312,  326,  321,  324,  323,  318,  321,  320,  330,  345,
      234,  324,  327,  332,    0,  328,  324,  682,  313,  310,
      682,  297,  682,  682,    0,  310,  307,    0,  294,    0,
        0,  682,  298,  682,    0,  297,    0,  302,  301,  287,
      286,  298,  287,  682,  296,  285,    0,  682,  297,  294,
      682,  281,  682,  682,    0,  294,  291,    0,  278,    0,
        0,  275,  682,  278,  273,    0,  276,  313,  300,  303,
      308,    0,  290,    0,  296,  296,  283,  267,  269,  280,
      264,  266,  267,  266,  682,    0,  270,  267,  251,  682,

      248,    0,  262,  244,  244,  253,  229,  231,  242,  229,
      240,  227,  249,  257,  254,  251,  247,    0,    0,  682,
      221,  682,    0,  220,    0,  682,    0,  214,  213,  222,
      218,  682,  212,  682,    0,  211,    0,  213,  682,  179,
        0,  201,  192,  182,  189,  187,  144,  121,   99,   92,
      682,    0,   93,   86,  682,    0,    0,  110,    0,  102,
       87,  682,    0,  682,    0,  682,    0,   90,  247,    0,
        0,    0,   67,   49,    0,  682,   64,  279,  282,  285,
      288,  291,  294,  297,  300,  303,  306
    } ;

static yyconst flex_int16_t yy_def[588] =
    {   0,
      576,    1,  576,  576,  576,  576,  577,  576,  576,  576,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  576,  576,  577,  578,  576,  576,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  576,  579,  576,  578,  576,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  576,  577,  577,  577,  577,
      577,  577,  577,  577,  580,  577,  577,  577,  577,  581,
      577,  577,  577,  577,  577,  582,  583,  577,  576,  577,
      577,  577,  584,  577,  576,  577,  577,  577,  577,  577,

      577,  576,  577,  576,  577,  577,  576,  577,  577,  577,
      576,  577,  577,  576,  576,  577,  577,  577,  577,  577,
      577,  585,  576,  576,  576,  576,  576,  577,  577,  577,
      577,  577,  576,  576,  576,  577,  577,  577,  577,  576,
      577,  577,  577,  576,  576,  576,  576,  577,  577,  577,
      577,  586,  576,  576,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  576,  577,  576,  576,  576,
      576,  576,  576,  576,  576,  577,  577,  577,  577,  577,
      577,  577,  577,  576,  576,  576,  577,  577,  577,  577,
      576,  577,  577,  577,  576,  576,  576,  576,  577,  577,

      577,  577,  576,  577,  576,  576,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  576,  576,
      576,  576,  576,  577,  577,  577,  577,  577,  576,  576,
      576,  576,  576,  576,  576,  577,  577,  577,  577,  577,
      577,  577,  576,  576,  576,  577,  577,  577,  587,  576,
      577,  576,  576,  576,  576,  577,  577,  577,  577,  576,
      576,  576,  576,  576,  577,  577,  577,  577,  577,  576,
      576,  576,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  576,  576,  576,  576,  576,
      576,  576,  576,  577,  577,  577,  577,  577,  577,  577,

      577,  576,  576,  576,  576,  576,  576,  576,  577,  577,
      577,  577,  577,  577,  577,  576,  576,  576,  577,  577,
      577,  576,  577,  576,  577,  576,  576,  576,  576,  577,
      577,  577,  577,  576,  576,  576,  576,  576,  576,  576,
      576,  577,  577,  577,  577,  577,  577,  577,  577,  576,
      576,  576,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  576,  576,  576,  576,  576,  576,
      576,  577,  577,  577,  577,  577,  577,  577,  576,  576,
      576,  577,  577,  577,  576,  576,  577,  577,  576,  577,
      576,  577,  576,  576,  576,  577,  577,  577,  576,  576,

      576,  576,  576,  576,  576,  577,  577,  577,  577,  577,
      577,  577,  576,  576,  576,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  576,  576,  576,
      576,  576,  576,  576,  577,  577,  577,  577,  577,  577,
      577,  576,  576,  576,  577,  577,  577,  576,  577,  576,
      577,  576,  576,  576,  577,  577,  577,  576,  576,  576,
      576,  576,  576,  576,  577,  577,  577,  577,  577,  577,
      577,  576,  576,  576,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  576,  576,  576,  577,
      577,  577,  576,  577,  576,  577,  576,  577,  576,  576,

      577,  577,  576,  576,  576,  577,  577,  577,  576,  576,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  576,
      576,  576,  577,  577,  577,  576,  577,  576,  577,  576,
      577,  576,  576,  576,  577,  577,  577,  576,  576,  577,
      577,  577,  577,  577,  577,  577,  576,  577,  576,  577,
      576,  577,  576,  577,  576,  577,  577,  577,  577,  577,
      577,  576,  577,  576,  577,  576,  577,  577,  577,  577,
      577,  577,  577,  577,  577,    0,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576
    } ;

static yyconst flex_int16_t yy_nxt[740] =
    {   0,
        4,    5,    5,    6,    4,    7,    8,    8,    9,   10,
       11,   12,   11,   11,   11,   11,   11,   11,   11,   11,
       13,   11,   11,   11,   11,   14,   15,   11,   11,   11,
       11,   11,   11,   16,   17,   11,   18,   11,   11,   11,
       11,   11,   19,   11,   20,   11,   21,   22,   11,   23,
       11,   11,   11,   11,   11,   24,   11,   25,   25,   26,
       26,   29,   39,   30,   30,   43,   27,   40,   25,   25,
       46,  575,   26,   26,   47,   47,   48,   47,   44,   50,
       50,   57,   47,   47,   29,  574,   30,   30,   66,   66,
       50,   50,  419,   58,   47,   47,   48,   47,   66,   66,

      420,  571,   47,   47,   89,   89,  114,   89,   95,   95,
      115,   95,   89,   89,  570,  569,   95,   95,  102,  102,
      116,  102,  104,  104,  117,  104,  102,  102,  568,  567,
      104,  104,  111,  111,  123,  111,  566,  565,  124,  125,
      111,  111,  270,  128,  564,  126,  127,  129,  130,  133,
      169,  144,  136,  134,  131,  132,  137,  145,  146,  271,
      148,  147,  170,  174,  563,  135,  149,  150,  138,  160,
      151,  166,  166,  175,  166,  161,  162,  163,  164,  166,
      166,  172,  177,  165,  173,  180,  182,  562,  181,  203,
      203,  213,  203,  273,  178,  219,  183,  203,  203,  220,

      221,  561,  214,  560,  224,  559,  222,  223,  225,  226,
      274,  287,  558,  260,  557,  227,  228,  261,  262,  292,
      295,  556,  265,  288,  263,  264,  266,  267,  290,  293,
      300,  291,  296,  268,  269,  298,  322,  322,  299,  322,
      301,  335,  340,  338,  322,  322,  339,  343,  346,  480,
      348,  347,  341,  336,  572,  555,  554,  553,  552,  344,
      349,  481,  551,  550,  549,  548,  547,  546,  545,  544,
      543,  542,  541,  540,  539,  538,  537,  536,  573,   49,
       49,   49,   47,   47,   47,   90,  535,   90,   96,  534,
       96,  103,  533,  103,  105,  532,  105,  112,  531,  112,

      167,  530,  167,  204,  529,  204,  323,  528,  323,  527,
      526,  525,  524,  523,  522,  521,  520,  519,  518,  517,
      516,  515,  514,  513,  512,  511,  510,  509,  508,  507,
      506,  505,  504,  503,  502,  501,  500,  499,  498,  497,
      496,  495,  494,  493,  492,  491,  490,  489,  488,  487,
      486,  485,  484,  483,  482,  479,  478,  477,  476,  475,
      474,  473,  472,  471,  470,  469,  468,  467,  466,  465,
      464,  463,  462,  461,  460,  459,  458,  457,  456,  455,
      454,  453,  452,  451,  450,  449,  448,  447,  446,  445,
      444,  443,  442,  441,  440,  439,  438,  437,  436,  435,

      434,  433,  432,  431,  430,  429,  428,  427,  426,  425,
      424,  423,  422,  421,  418,  417,  416,  415,  414,  413,
      412,  411,  410,  409,  408,  407,  406,  405,  404,  403,
      402,  401,  400,  399,  398,  397,  396,  395,  394,  393,
      392,  391,  390,  389,  388,  387,  386,  385,  384,  383,
      382,  381,  380,  379,  378,  377,  376,  375,  374,  373,
      372,  371,  370,  369,  368,  367,  366,  365,  364,  363,
      362,  361,  360,  359,  358,  357,  356,  355,  354,  353,
      352,  351,  350,  345,  342,  337,  334,  333,  332,  331,
      330,  329,  328,  327,  326,  325,  324,  321,  320,  319,

      318,  317,  316,  315,  314,  313,  312,  311,  310,  309,
      308,  307,  306,  305,  304,  303,  302,  297,  294,  289,
      286,  285,  284,  283,  282,  281,  280,  279,  278,  277,
      276,  275,  272,  259,  258,  257,  256,  255,  254,  253,
      252,  251,  250,  249,  248,  247,  246,  245,  244,  243,
      242,  241,  240,  239,  238,  237,  236,  235,  234,  233,
      232,  231,  230,  229,  218,  217,  216,  215,  212,  211,
      210,  209,  208,  207,  206,  205,  202,  201,  200,  199,
      198,  197,  196,  195,  194,  193,  192,  191,  190,  189,
      188,  187,  186,  185,  184,  179,  176,  171,  168,  159,

      158,  157,  156,  155,  154,  153,  152,  143,  142,  141,
      140,  139,  122,  121,  120,  119,  118,  113,  110,  109,
      108,  107,  106,  101,  100,   99,   98,   97,   94,   93,
       92,   91,   88,   87,   86,   85,   84,   83,   82,   81,
       80,   79,   78,   77,   76,   75,   74,   73,   72,   71,
       70,   69,   68,   67,   48,   65,   64,   63,   62,   61,
       60,   59,   56,   55,   54,   53,   52,   51,   45,   42,
       41,   38,   37,   36,   35,   34,   33,   32,   31,   28,
      576,    3,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,

      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576
    } ;

static yyconst flex_int16_t yy_chk[740] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    5,    5,    6,
        6,    8,   20,    8,    8,   23,  577,   20,   25,   25,
       26,  574,   26,   26,   28,   28,   28,   28,   23,   29,
       29,   37,   28,   28,   30,  573,   30,   30,   46,   46,
       50,   50,  356,   37,   49,   49,   49,   49,   66,   66,

      356,  568,   49,   49,   75,   75,   95,   75,   80,   80,
       95,   80,   75,   75,  561,  560,   80,   80,   86,   86,
       96,   86,   87,   87,   96,   87,   86,   86,  558,  554,
       87,   87,   93,   93,  102,   93,  553,  550,  102,  102,
       93,   93,  205,  103,  549,  102,  102,  103,  103,  104,
      124,  111,  105,  104,  103,  103,  105,  111,  111,  205,
      112,  111,  124,  127,  548,  104,  112,  112,  105,  121,
      112,  122,  122,  127,  122,  121,  121,  121,  121,  122,
      122,  126,  129,  121,  126,  131,  132,  547,  131,  152,
      152,  161,  152,  207,  129,  166,  132,  152,  152,  166,

      166,  546,  161,  545,  167,  544,  166,  166,  167,  167,
      207,  220,  543,  203,  542,  167,  167,  203,  203,  223,
      225,  540,  204,  220,  203,  203,  204,  204,  222,  223,
      228,  222,  225,  204,  204,  227,  249,  249,  227,  249,
      228,  261,  264,  263,  249,  249,  263,  266,  268,  421,
      269,  268,  264,  261,  569,  538,  536,  533,  531,  266,
      269,  421,  530,  529,  528,  524,  521,  517,  516,  515,
      514,  513,  512,  511,  510,  509,  508,  507,  569,  578,
      578,  578,  579,  579,  579,  580,  506,  580,  581,  505,
      581,  582,  504,  582,  583,  503,  583,  584,  501,  584,

      585,  499,  585,  586,  498,  586,  587,  497,  587,  494,
      493,  492,  491,  490,  489,  488,  487,  486,  485,  483,
      481,  480,  479,  478,  477,  475,  474,  472,  469,  467,
      466,  462,  460,  459,  456,  455,  453,  452,  451,  450,
      449,  448,  446,  443,  439,  437,  436,  432,  430,  429,
      427,  426,  424,  423,  422,  420,  419,  418,  417,  416,
      415,  414,  413,  412,  411,  410,  409,  408,  407,  406,
      405,  404,  403,  402,  401,  400,  399,  398,  397,  396,
      395,  394,  393,  390,  389,  388,  386,  384,  383,  382,
      381,  380,  379,  378,  377,  376,  375,  374,  373,  372,

      371,  370,  369,  368,  367,  366,  365,  364,  363,  362,
      361,  360,  359,  357,  355,  354,  353,  352,  351,  350,
      349,  347,  346,  345,  344,  343,  342,  341,  339,  338,
      337,  336,  335,  334,  333,  331,  330,  329,  327,  326,
      325,  324,  323,  322,  321,  319,  318,  316,  313,  311,
      310,  306,  304,  303,  301,  299,  298,  297,  296,  295,
      294,  293,  291,  290,  289,  288,  287,  286,  285,  284,
      283,  282,  281,  280,  279,  278,  277,  275,  274,  273,
      272,  271,  270,  267,  265,  262,  260,  259,  258,  257,
      256,  255,  254,  253,  252,  251,  250,  248,  247,  246,

      245,  244,  243,  242,  241,  240,  239,  238,  237,  236,
      235,  234,  233,  232,  231,  230,  229,  226,  224,  221,
      219,  218,  217,  216,  215,  214,  213,  212,  211,  210,
      209,  208,  206,  202,  201,  200,  199,  198,  197,  196,
      195,  192,  191,  190,  189,  188,  187,  186,  185,  184,
      183,  181,  180,  179,  178,  177,  176,  175,  173,  172,
      171,  170,  169,  168,  165,  164,  163,  162,  160,  159,
      158,  157,  156,  155,  154,  153,  151,  150,  149,  148,
      147,  146,  145,  144,  143,  142,  141,  140,  139,  138,
      137,  136,  135,  134,  133,  130,  128,  125,  123,  120,

      119,  118,  117,  116,  115,  114,  113,  110,  109,  108,
      107,  106,  101,  100,   99,   98,   97,   94,   92,   91,
       90,   89,   88,   85,   84,   83,   82,   81,   79,   78,
       77,   76,   74,   73,   72,   71,   70,   69,   68,   67,
       64,   63,   62,   61,   60,   59,   58,   57,   56,   55,
       54,   53,   52,   51,   47,   45,   44,   43,   42,   41,
       40,   38,   36,   35,   34,   33,   32,   31,   24,   22,
       21,   19,   18,   17,   16,   15,   14,   13,   12,    7,
        3,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,

      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int babs_flex_debug;
int babs_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *babstext;
#line 1 "babs_lexer.l"
#line 2 "babs_lexer.l"
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "babs_parser.h"
#line 836 "babs_lexer.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int babslex_destroy (void );

int babsget_debug (void );

void babsset_debug (int debug_flag  );

YY_EXTRA_TYPE babsget_extra (void );

void babsset_extra (YY_EXTRA_TYPE user_defined  );

FILE *babsget_in (void );

void babsset_in  (FILE * in_str  );

FILE *babsget_out (void );

void babsset_out  (FILE * out_str  );

int babsget_leng (void );

char *babsget_text (void );

int babsget_lineno (void );

void babsset_lineno (int line_number  );

YYSTYPE * babsget_lval (void );

void babsset_lval (YYSTYPE * yylval_param  );

       YYLTYPE *babsget_lloc (void );
    
        void babsset_lloc (YYLTYPE * yylloc_param  );
    
/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int babswrap (void );
#else
extern int babswrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( babstext, babsleng, 1, babsout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( babsin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( babsin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, babsin))==0 && ferror(babsin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(babsin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int babslex \
               (YYSTYPE * yylval_param,YYLTYPE * yylloc_param );

#define YY_DECL int babslex \
               (YYSTYPE * yylval_param, YYLTYPE * yylloc_param )
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after babstext and babsleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
        YYSTYPE * yylval;
    
        YYLTYPE * yylloc;
    
#line 15 "babs_lexer.l"

#line 1039 "babs_lexer.c"

    yylval = yylval_param;

    yylloc = yylloc_param;

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! babsin )
			babsin = stdin;

		if ( ! babsout )
			babsout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			babsensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				babs_create_buffer(babsin,YY_BUF_SIZE );
		}

		babs_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of babstext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 577 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 682 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 16 "babs_lexer.l"
; 
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 18 "babs_lexer.l"
return R_MARKOV;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 19 "babs_lexer.l"
return R_UNF;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 20 "babs_lexer.l"
return R_FILE;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 21 "babs_lexer.l"
return R_OTHER;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 22 "babs_lexer.l"
return R_MMPP;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 23 "babs_lexer.l"
return R_MMPP_R;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 24 "babs_lexer.l"
return R_POISSON;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 25 "babs_lexer.l"
return R_NORMAL;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 27 "babs_lexer.l"
return ARRIVAL_TYPE;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 28 "babs_lexer.l"
return ARRIVAL_LAMBDA;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 29 "babs_lexer.l"
return ARRIVAL_FROM;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 30 "babs_lexer.l"
return ARRIVAL_TO;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 31 "babs_lexer.l"
return ARRIVAL_SAVETO;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 32 "babs_lexer.l"
return ARRIVAL_LOADFROM;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 33 "babs_lexer.l"
return ARRIVAL_MEAN;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 34 "babs_lexer.l"
return ARRIVAL_SDEV;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 36 "babs_lexer.l"
return BURST_TYPE;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 37 "babs_lexer.l"
return BURST_LAMBDA;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 38 "babs_lexer.l"
return BURST_FROM;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 39 "babs_lexer.l"
return BURST_TO;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 40 "babs_lexer.l"
return BURST_SAVETO;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 41 "babs_lexer.l"
return BURST_LOADFROM;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 42 "babs_lexer.l"
return BURST_MEAN;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 43 "babs_lexer.l"
return BURST_SDEV;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 45 "babs_lexer.l"
return QUEUE_MAXLENGTH;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 46 "babs_lexer.l"
return QUEUE_SERVERS;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 47 "babs_lexer.l"
return QUEUE_KIND;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 48 "babs_lexer.l"
return QUEUE_WINDOW;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 49 "babs_lexer.l"
return BURST_FIFO_QUEUE;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 50 "babs_lexer.l"
return BURST_SCHED1_QUEUE;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 51 "babs_lexer.l"
return BURST_SCHEDWIN_QUEUE;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 53 "babs_lexer.l"
return SERVICE_TYPE;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 54 "babs_lexer.l"
return SERVICE_LAMBDA;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 55 "babs_lexer.l"
return SERVICE_TO;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 56 "babs_lexer.l"
return SERVICE_FROM;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 57 "babs_lexer.l"
return SERVICE_SAVETO;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 58 "babs_lexer.l"
return SERVICE_LOADFROM;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 59 "babs_lexer.l"
return SERVICE_MEAN;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 60 "babs_lexer.l"
return SERVICE_SDEV;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 62 "babs_lexer.l"
return DEPARTURE_SAVETO;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 64 "babs_lexer.l"
return STOP_MAXTIME;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 65 "babs_lexer.l"
return STOP_MAXARRIVAL;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 66 "babs_lexer.l"
return STOP_QUEUEZERO;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 68 "babs_lexer.l"
return PROTOCOL;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 69 "babs_lexer.l"
return PROTO_BABSQ;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 70 "babs_lexer.l"
return NTHREADS;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 72 "babs_lexer.l"
return DEBUG_ERROR;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 73 "babs_lexer.l"
return DEBUG_WARNING;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 74 "babs_lexer.l"
return DEBUG_INFO;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 75 "babs_lexer.l"
return LIBS_RANDOM;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 76 "babs_lexer.l"
return LIB_RAND_IRAND;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 77 "babs_lexer.l"
return LIB_RAND_RANDLIB;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 78 "babs_lexer.l"
return EQ;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 79 "babs_lexer.l"
return ENDLINE;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 80 "babs_lexer.l"
return YES;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 81 "babs_lexer.l"
return NO;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 82 "babs_lexer.l"
{yylval->dval = atof(babstext); return REALNUM;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 83 "babs_lexer.l"
{yylval->dval = atof(babstext); return REALNUM;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 84 "babs_lexer.l"
{yylval->ival = atoi(babstext); return INTNUM;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 85 "babs_lexer.l"
{yylval->ival = atoi(babstext); return INTNUM;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 86 "babs_lexer.l"
{yylval->str = strdup(babstext); return STRING;}
	YY_BREAK
case 63:
/* rule 63 can match eol */
YY_RULE_SETUP
#line 89 "babs_lexer.l"
;       /* ignore whitespace */ 
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 91 "babs_lexer.l"
ECHO;
	YY_BREAK
#line 1448 "babs_lexer.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed babsin at a new source and called
			 * babslex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = babsin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( babswrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * babstext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of babslex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					babsrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			babsrestart(babsin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) babsrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 577 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 577 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 576);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up babstext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					babsrestart(babsin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( babswrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve babstext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void babsrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        babsensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            babs_create_buffer(babsin,YY_BUF_SIZE );
	}

	babs_init_buffer(YY_CURRENT_BUFFER,input_file );
	babs_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void babs_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		babspop_buffer_state();
	 *		babspush_buffer_state(new_buffer);
     */
	babsensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	babs_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (babswrap()) processing, but the only time this flag
	 * is looked at is after babswrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void babs_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	babsin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE babs_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) babsalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in babs_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) babsalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in babs_create_buffer()" );

	b->yy_is_our_buffer = 1;

	babs_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with babs_create_buffer()
 * 
 */
    void babs_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		babsfree((void *) b->yy_ch_buf  );

	babsfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a babsrestart() or at EOF.
 */
    static void babs_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	babs_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then babs_init_buffer was _probably_
     * called from babsrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void babs_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		babs_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void babspush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	babsensure_buffer_stack();

	/* This block is copied from babs_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from babs_switch_to_buffer. */
	babs_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void babspop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	babs_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		babs_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void babsensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)babsalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in babsensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)babsrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in babsensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE babs_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) babsalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in babs_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	babs_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to babslex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       babs_scan_bytes() instead.
 */
YY_BUFFER_STATE babs_scan_string (yyconst char * yystr )
{
    
	return babs_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to babslex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE babs_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) babsalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in babs_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = babs_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in babs_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up babstext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		babstext[babsleng] = (yy_hold_char); \
		(yy_c_buf_p) = babstext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		babsleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int babsget_lineno  (void)
{
        
    return babslineno;
}

/** Get the input stream.
 * 
 */
FILE *babsget_in  (void)
{
        return babsin;
}

/** Get the output stream.
 * 
 */
FILE *babsget_out  (void)
{
        return babsout;
}

/** Get the length of the current token.
 * 
 */
int babsget_leng  (void)
{
        return babsleng;
}

/** Get the current token.
 * 
 */

char *babsget_text  (void)
{
        return babstext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void babsset_lineno (int  line_number )
{
    
    babslineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see babs_switch_to_buffer
 */
void babsset_in (FILE *  in_str )
{
        babsin = in_str ;
}

void babsset_out (FILE *  out_str )
{
        babsout = out_str ;
}

int babsget_debug  (void)
{
        return babs_flex_debug;
}

void babsset_debug (int  bdebug )
{
        babs_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from babslex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    babsin = stdin;
    babsout = stdout;
#else
    babsin = (FILE *) 0;
    babsout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * babslex_init()
     */
    return 0;
}

/* babslex_destroy is for both reentrant and non-reentrant scanners. */
int babslex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		babs_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		babspop_buffer_state();
	}

	/* Destroy the stack itself. */
	babsfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * babslex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *babsalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *babsrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void babsfree (void * ptr )
{
	free( (char *) ptr );	/* see babsrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 91 "babs_lexer.l"




