#line 2 "lexer.c"

#line 4 "lexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 56
#define YY_END_OF_BUFFER 57
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[557] =
    {   0,
        0,    0,   57,   56,   55,   56,   54,   53,   47,   46,
       54,   54,   54,   54,   54,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   55,   52,
       54,   54,    0,   53,   54,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   49,   54,   54,
       54,   54,   54,   54,    0,    0,    1,   54,   51,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   54,   48,
       50,   37,   54,   54,   54,   54,   54,    4,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   54,   54,

       54,   54,   54,   54,   54,   54,   54,   54,   54,    0,
       54,   54,   54,    0,   54,   54,   54,   54,   54,   54,
        0,   54,   54,   54,   54,   54,   54,    3,   54,   54,
        0,    0,    0,    0,    0,   54,   54,   54,   54,   54,
        0,   54,   54,    0,   54,   54,   54,   54,    0,   54,
       54,    0,    0,   54,   54,   54,   54,   54,   54,   54,
        5,   54,    0,    0,    0,    0,    0,   54,   54,   54,
       54,   54,    0,    0,    0,   54,   54,   54,   54,    0,
       54,   54,   54,   54,    0,    0,    0,   54,   54,   54,
       54,    0,    0,   54,   54,   54,   54,   54,   54,   54,

       54,   54,   54,    0,   54,    0,    0,    0,    0,    0,
       54,   54,   54,   54,   54,    0,    0,    0,   54,   54,
       54,   54,    0,   54,    2,   39,   35,    0,    0,    0,
       54,   54,   54,    0,   54,    0,    0,   54,   54,   54,
       38,   36,   54,   54,   54,   54,   54,    0,    0,    0,
        0,   54,   54,   54,   54,    0,    0,    0,    0,    0,
       54,   54,   54,   54,   54,    0,    0,    0,   54,   54,
       54,   54,    0,   54,    0,    0,    0,   54,   54,   54,
        0,    0,    0,    0,   54,   54,   54,   54,    0,    0,
        0,   54,   54,   54,   54,   19,   54,   54,   54,   54,

        0,    0,    0,    0,   13,    0,   54,   54,   54,   54,
       13,   54,    0,    0,    0,    0,    0,   54,   54,   54,
       54,   54,    0,   42,    0,   54,   42,   54,    0,   54,
        0,   54,    0,    0,   18,   54,   54,   18,    0,    0,
        0,    0,   22,    0,   54,   54,   54,   54,   22,   54,
        0,    0,    0,   54,   54,   54,   54,    8,   54,   54,
       54,    0,    0,    0,    0,    0,   54,   54,   54,   54,
       54,    0,    0,    0,    0,    0,   54,   54,   54,   54,
       54,   40,    0,   40,   54,    0,   54,   43,   43,    0,
        0,   54,   54,    0,    0,    0,    0,    0,   54,   54,

       54,   54,   54,    0,    0,    0,   54,   54,   54,   54,
       54,   54,    9,   54,   12,    0,    0,    0,   10,   12,
       54,   54,   54,   10,    0,    0,    0,    0,    0,   54,
       54,   54,   54,   54,    0,   54,    0,   54,    0,    0,
       54,   54,   23,    0,    0,    0,   20,   23,   54,   54,
       54,   20,    0,   27,    0,   54,   27,   54,   54,   54,
        6,   54,    0,    0,    0,   54,   54,   54,    0,    0,
        0,    0,   32,   54,   54,   54,   54,   32,   41,   41,
        0,   54,    0,   17,   54,   17,    0,    0,    0,   54,
       54,   54,    0,    0,   54,   54,   54,   54,    7,   11,

        0,   14,   11,   54,   14,   33,    0,   30,    0,   33,
       54,   30,   54,    0,   54,    0,   54,   21,    0,   24,
       21,   54,   24,    0,   29,   54,   29,   54,   54,    0,
       54,   34,    0,   34,   54,    0,   54,   16,   16,    0,
       54,   28,   28,   44,   54,   15,   15,   31,   31,   26,
       26,   25,   25,   54,   45,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    4,    5,    6,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    1,    8,    1,
        9,    1,    1,    1,   10,   11,   12,   13,   14,   15,
       16,   17,   18,   16,   19,   20,   21,   22,   23,   16,
       24,   25,   26,   27,   28,   29,   16,   16,   16,   16,
        1,    1,    1,    1,   30,    1,   31,   32,   33,   34,

       35,   36,   37,   38,   39,   16,   40,   41,   42,   43,
       44,   45,   46,   47,   48,   49,   50,   51,   52,   53,
       54,   55,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[56] =
    {   0,
        1,    1,    2,    1,    3,    3,    3,    1,    1,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3
    } ;

static yyconst flex_int16_t yy_base[568] =
    {   0,
        0,    0,  647,  648,   54,  639,  639,   53,  648,  648,
        0,  618,  625,  628,  619,  612,  629,   41,  613,  590,
      588,  600,  595,   17,  586,  582,   27,  596,   65,   58,
        0,   69,  623,   74,  608,  617,  600,  612,  611,  602,
      601,  594,  611,  573,  577,   37,  586,  583,  578,  571,
      579,  566,  568,  563,  603,  606,  648,   82,  601,  597,
      576,  575,  574,  575,  589,  582,  575,  577,  559,  566,
      546,  564,  546,  558,  545,  542,  540,  538,  543,    0,
      580,    0,  561,  561,  560,  569,  559,    0,  569,  554,
      528,   91,  541,  530,  100,  527,  540,  530,  538,  533,

      109,  561,  542,  541,  538,  546,  552,  547,  533,   79,
       83,  128,  514,  515,  514,  506,  528,  525,  137,  524,
       52,   61,  534,  541,  540,  538,  522,    0,  524,  509,
      505,  517,  499,  499,  504,  500,  512,  494,  494,  499,
      105,  108,  489,  507,  506,  491,  501,  490,  100,  110,
      498,  501,  481,  499,  479,  515,  499,  498,  507,  140,
        0,  163,  483,  470,  473,  477,  476,  478,  465,  468,
      472,  471,  467,  470,  481,  464,  467,  478,  461,  464,
      463,  470,  456,  462,  471,  466,  446,  468,  463,  443,
      172,  443,  460,  441,  458,  469,  477,  476,  474,  470,

      477,  459,  463,   39,  134,  443,  451,  451,  449,  431,
      438,  446,  446,  444,  426,  427,  437,  425,  424,  434,
      422,  433,  433,  432,    0,    0,    0,  412,  417,  418,
      409,  414,  415,  143,  149,   65,  409,   66,  408,  436,
        0,    0,  433,  435,  429,  436,  434,  404,   75,  419,
       79,  402,  122,  417,  133,  408,  415,  396,  413,  394,
      403,  410,  391,  408,  389,  393,  392,  392,  390,  389,
      389,  192,  387,  386,  388,  377,  392,  385,  374,  389,
      376,  125,  391,  134,  374,  155,  389,  151,  372,  379,
      382,  369,  376,  379,  383,    0,  398,  392,  396,  394,

      364,  365,  375,  354,  648,  359,  359,  360,  370,  349,
        0,  354,  350,  364,  357,  363,  355,  345,  359,  352,
      358,  350,  341,  648,  348,  339,    0,  346,  336,  335,
      340,  339,  345,  344,  648,  343,  342,    0,  332,  333,
      343,  322,  648,  327,  327,  328,  338,  317,    0,  322,
      319,  323,  309,  316,  320,  306,  184,    0,  337,  334,
      335,  315,  324,  321,  319,  318,  310,  319,  316,  314,
      313,  308,  306,  301,  305,  301,  303,  301,  296,  300,
      296,  648,  294,    0,  293,  304,  303,  648,    0,  290,
      285,  288,  283,  287,  296,  293,  291,  290,  282,  291,

      288,  286,  285,  280,  283,  282,  277,  280,  279,  288,
      302,  282,    0,  285,  648,  275,  272,  258,  648,    0,
      272,  269,  255,    0,  259,  258,  258,  259,  264,  254,
      253,  253,  254,  259,  256,  255,  240,  239,  252,  240,
      250,  238,  648,  251,  248,  234,  648,    0,  248,  245,
      231,    0,  228,  648,  231,  226,    0,  229,  265,  252,
        0,  252,  241,  224,  226,  238,  221,  223,  223,  229,
      216,  224,  648,  219,  225,  212,  220,    0,  648,    0,
      223,  222,  207,  648,  206,    0,  223,  206,  208,  220,
      203,  205,  217,  203,  215,  201,  222,  230,    0,  648,

      198,  648,    0,  197,    0,  648,  204,  648,  189,    0,
      199,    0,  183,  180,  177,  185,  182,  648,  173,  648,
        0,  164,    0,  166,  648,  165,    0,  191,  183,  147,
      120,  648,  100,    0,   97,  106,   91,  648,    0,   92,
       78,  648,    0,    0,   87,  648,    0,  648,    0,  648,
        0,  648,    0,   78,    0,  648,   71,  209,  212,  215,
      218,  221,  224,  227,  230,  233,  236
    } ;

static yyconst flex_int16_t yy_def[568] =
    {   0,
      556,    1,  556,  556,  556,  556,  557,  556,  556,  556,
      557,  557,  557,  557,  557,  557,  557,  557,  557,  557,
      557,  557,  557,  557,  557,  557,  557,  557,  556,  556,
      557,  558,  556,  556,  557,  557,  557,  557,  557,  557,
      557,  557,  557,  557,  557,  557,  557,  557,  557,  557,
      557,  557,  557,  557,  556,  559,  556,  558,  556,  557,
      557,  557,  557,  557,  557,  557,  557,  557,  557,  557,
      557,  557,  557,  557,  557,  557,  557,  557,  557,  557,
      556,  557,  557,  557,  557,  557,  557,  557,  557,  557,
      557,  560,  557,  557,  561,  557,  557,  557,  557,  557,

      562,  557,  557,  557,  557,  557,  557,  557,  557,  556,
      557,  563,  557,  556,  557,  557,  557,  557,  564,  557,
      556,  557,  557,  557,  557,  557,  557,  557,  557,  557,
      556,  556,  556,  556,  556,  557,  557,  557,  557,  557,
      556,  557,  557,  556,  557,  557,  557,  557,  556,  557,
      557,  556,  556,  557,  557,  557,  557,  557,  557,  557,
      557,  565,  556,  556,  556,  556,  556,  557,  557,  557,
      557,  557,  556,  556,  556,  557,  557,  557,  557,  556,
      557,  557,  557,  557,  556,  556,  556,  557,  557,  557,
      566,  556,  556,  557,  557,  557,  557,  557,  557,  557,

      557,  557,  557,  556,  557,  556,  556,  556,  556,  556,
      557,  557,  557,  557,  557,  556,  556,  556,  557,  557,
      557,  557,  556,  557,  557,  557,  557,  556,  556,  556,
      557,  557,  557,  556,  557,  556,  556,  557,  557,  557,
      557,  557,  557,  557,  557,  557,  557,  556,  556,  556,
      556,  557,  557,  557,  557,  556,  556,  556,  556,  556,
      557,  557,  557,  557,  557,  556,  556,  556,  557,  557,
      557,  567,  556,  557,  556,  556,  556,  557,  557,  557,
      556,  556,  556,  556,  557,  557,  557,  557,  556,  556,
      556,  557,  557,  557,  557,  557,  557,  557,  557,  557,

      556,  556,  556,  556,  556,  556,  557,  557,  557,  557,
      557,  557,  556,  556,  556,  556,  556,  557,  557,  557,
      557,  557,  556,  556,  556,  557,  557,  557,  556,  557,
      556,  557,  556,  556,  556,  557,  557,  557,  556,  556,
      556,  556,  556,  556,  557,  557,  557,  557,  557,  557,
      556,  556,  556,  557,  557,  557,  557,  557,  557,  557,
      557,  556,  556,  556,  556,  556,  557,  557,  557,  557,
      557,  556,  556,  556,  556,  556,  557,  557,  557,  557,
      557,  556,  556,  557,  557,  556,  557,  556,  557,  556,
      556,  557,  557,  556,  556,  556,  556,  556,  557,  557,

      557,  557,  557,  556,  556,  556,  557,  557,  557,  557,
      557,  557,  557,  557,  556,  556,  556,  556,  556,  557,
      557,  557,  557,  557,  556,  556,  556,  556,  556,  557,
      557,  557,  557,  557,  556,  557,  556,  557,  556,  556,
      557,  557,  556,  556,  556,  556,  556,  557,  557,  557,
      557,  557,  556,  556,  556,  557,  557,  557,  557,  557,
      557,  557,  556,  556,  556,  557,  557,  557,  556,  556,
      556,  556,  556,  557,  557,  557,  557,  557,  556,  557,
      556,  557,  556,  556,  557,  557,  556,  556,  556,  557,
      557,  557,  556,  556,  557,  557,  557,  557,  557,  556,

      556,  556,  557,  557,  557,  556,  556,  556,  556,  557,
      557,  557,  557,  556,  557,  556,  557,  556,  556,  556,
      557,  557,  557,  556,  556,  557,  557,  557,  557,  556,
      557,  556,  556,  557,  557,  556,  557,  556,  557,  556,
      557,  556,  557,  557,  557,  556,  557,  556,  557,  556,
      557,  556,  557,  557,  557,    0,  556,  556,  556,  556,
      556,  556,  556,  556,  556,  556,  556
    } ;

static yyconst flex_int16_t yy_nxt[704] =
    {   0,
        4,    5,    5,    6,    4,    7,    8,    9,   10,   11,
       11,   12,   11,   11,   11,   11,   11,   11,   11,   13,
       11,   14,   15,   16,   17,   18,   19,   11,   11,   11,
       20,   11,   21,   22,   11,   11,   11,   11,   11,   11,
       23,   11,   24,   11,   25,   26,   11,   27,   11,   11,
       11,   11,   11,   28,   11,   29,   29,   33,   41,   34,
       48,   52,   55,   42,   30,   49,   29,   29,   71,   56,
       56,   57,   56,   31,  248,   53,   56,   56,   33,  249,
       34,   72,   56,   56,   57,   56,  250,  251,  555,   56,
       56,  110,  110,  152,  110,  289,  292,  153,  110,  110,

      114,  114,  154,  114,  554,  302,  155,  114,  114,  121,
      121,  131,  121,  290,  293,  136,  121,  121,  303,  553,
      132,  133,  305,  134,  137,  138,  135,  139,  141,  141,
      140,  141,  306,  552,  551,  141,  141,  149,  149,  173,
      149,  185,  176,  174,  149,  149,  177,  186,  187,  550,
      549,  188,  308,  548,  200,  340,  175,  189,  190,  178,
      201,  547,  202,  204,  204,  309,  204,  203,  341,  252,
      204,  204,  234,  234,  253,  234,  311,  343,  281,  234,
      234,  254,  255,  282,  285,  346,  312,  344,  546,  286,
      283,  284,  329,  329,  349,  329,  287,  288,  347,  329,

      329,  410,  545,  544,  350,  543,  542,  541,  411,   58,
       58,   58,   56,   56,   56,  111,  540,  111,  115,  539,
      115,  122,  538,  122,  142,  537,  142,  150,  536,  150,
      205,  535,  205,  235,  534,  235,  330,  533,  330,  532,
      531,  530,  529,  528,  527,  526,  525,  524,  523,  522,
      521,  520,  519,  518,  517,  516,  515,  514,  513,  512,
      511,  510,  509,  508,  507,  506,  505,  504,  503,  502,
      501,  500,  499,  498,  497,  496,  495,  494,  493,  492,
      491,  490,  489,  488,  487,  486,  485,  484,  483,  482,
      481,  480,  479,  478,  477,  476,  475,  474,  473,  472,

      471,  470,  469,  468,  467,  466,  465,  464,  463,  462,
      461,  460,  459,  458,  457,  456,  455,  454,  453,  452,
      451,  450,  449,  448,  447,  446,  445,  444,  443,  442,
      441,  440,  439,  438,  437,  436,  435,  434,  433,  432,
      431,  430,  429,  428,  427,  426,  425,  424,  423,  422,
      421,  420,  419,  418,  417,  416,  415,  414,  413,  412,
      409,  408,  407,  406,  405,  404,  403,  402,  401,  400,
      399,  398,  397,  396,  395,  394,  393,  392,  391,  390,
      389,  388,  387,  386,  385,  384,  383,  382,  381,  380,
      379,  378,  377,  376,  375,  374,  373,  372,  371,  370,

      369,  368,  367,  366,  365,  364,  363,  362,  361,  360,
      359,  358,  357,  356,  355,  354,  353,  352,  351,  348,
      345,  342,  339,  338,  337,  336,  335,  334,  333,  332,
      331,  328,  327,  326,  325,  324,  323,  322,  321,  320,
      319,  318,  317,  316,  315,  314,  313,  310,  307,  304,
      301,  300,  299,  298,  297,  296,  295,  294,  291,  280,
      279,  278,  277,  276,  275,  274,  273,  272,  271,  270,
      269,  268,  267,  266,  265,  264,  263,  262,  261,  260,
      259,  258,  257,  256,  247,  246,  245,  244,  243,  242,
      241,  240,  239,  238,  237,  236,  233,  232,  231,  230,

      229,  228,  227,  226,  225,  224,  223,  222,  221,  220,
      219,  218,  217,  216,  215,  214,  213,  212,  211,  210,
      209,  208,  207,  206,  199,  198,  197,  196,  195,  194,
      193,  192,  191,  184,  183,  182,  181,  180,  179,  172,
      171,  170,  169,  168,  167,  166,  165,  164,  163,  162,
      161,  160,  159,  158,  157,  156,  151,  148,  147,  146,
      145,  144,  143,  130,  129,  128,  127,  126,  125,  124,
      123,  120,  119,  118,  117,  116,  113,  112,  109,  108,
      107,  106,  105,  104,  103,  102,   81,  101,  100,   99,
       98,   97,   96,   95,   94,   93,   92,   91,   90,   89,

       88,   87,   86,   85,   84,   83,   82,   59,   57,   81,
       80,   79,   78,   77,   76,   75,   74,   73,   70,   69,
       68,   67,   66,   65,   64,   63,   62,   61,   60,   59,
       54,   51,   50,   47,   46,   45,   44,   43,   40,   39,
       38,   37,   36,   35,   32,   30,  556,    3,  556,  556,
      556,  556,  556,  556,  556,  556,  556,  556,  556,  556,
      556,  556,  556,  556,  556,  556,  556,  556,  556,  556,
      556,  556,  556,  556,  556,  556,  556,  556,  556,  556,
      556,  556,  556,  556,  556,  556,  556,  556,  556,  556,
      556,  556,  556,  556,  556,  556,  556,  556,  556,  556,

      556,  556,  556
    } ;

static yyconst flex_int16_t yy_chk[704] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    5,    5,    8,   18,    8,
       24,   27,   30,   18,   30,   24,   29,   29,   46,   32,
       32,   32,   32,  557,  204,   27,   32,   32,   34,  204,
       34,   46,   58,   58,   58,   58,  204,  204,  554,   58,
       58,   92,   92,  121,   92,  236,  238,  121,   92,   92,

       95,   95,  122,   95,  545,  249,  122,   95,   95,  101,
      101,  110,  101,  236,  238,  111,  101,  101,  249,  541,
      110,  110,  251,  110,  111,  111,  110,  111,  112,  112,
      111,  112,  251,  540,  537,  112,  112,  119,  119,  141,
      119,  149,  142,  141,  119,  119,  142,  149,  149,  536,
      535,  150,  253,  533,  160,  282,  141,  150,  150,  142,
      160,  531,  160,  162,  162,  253,  162,  160,  282,  205,
      162,  162,  191,  191,  205,  191,  255,  284,  234,  191,
      191,  205,  205,  234,  235,  286,  255,  284,  530,  235,
      234,  234,  272,  272,  288,  272,  235,  235,  286,  272,

      272,  357,  529,  528,  288,  526,  524,  522,  357,  558,
      558,  558,  559,  559,  559,  560,  519,  560,  561,  517,
      561,  562,  516,  562,  563,  515,  563,  564,  514,  564,
      565,  513,  565,  566,  511,  566,  567,  509,  567,  507,
      504,  501,  498,  497,  496,  495,  494,  493,  492,  491,
      490,  489,  488,  487,  485,  483,  482,  481,  477,  476,
      475,  474,  472,  471,  470,  469,  468,  467,  466,  465,
      464,  463,  462,  460,  459,  458,  456,  455,  453,  451,
      450,  449,  446,  445,  444,  442,  441,  440,  439,  438,
      437,  436,  435,  434,  433,  432,  431,  430,  429,  428,

      427,  426,  425,  423,  422,  421,  418,  417,  416,  414,
      412,  411,  410,  409,  408,  407,  406,  405,  404,  403,
      402,  401,  400,  399,  398,  397,  396,  395,  394,  393,
      392,  391,  390,  387,  386,  385,  383,  381,  380,  379,
      378,  377,  376,  375,  374,  373,  372,  371,  370,  369,
      368,  367,  366,  365,  364,  363,  362,  361,  360,  359,
      356,  355,  354,  353,  352,  351,  350,  348,  347,  346,
      345,  344,  342,  341,  340,  339,  337,  336,  334,  333,
      332,  331,  330,  329,  328,  326,  325,  323,  322,  321,
      320,  319,  318,  317,  316,  315,  314,  313,  312,  310,

      309,  308,  307,  306,  304,  303,  302,  301,  300,  299,
      298,  297,  295,  294,  293,  292,  291,  290,  289,  287,
      285,  283,  281,  280,  279,  278,  277,  276,  275,  274,
      273,  271,  270,  269,  268,  267,  266,  265,  264,  263,
      262,  261,  260,  259,  258,  257,  256,  254,  252,  250,
      248,  247,  246,  245,  244,  243,  240,  239,  237,  233,
      232,  231,  230,  229,  228,  224,  223,  222,  221,  220,
      219,  218,  217,  216,  215,  214,  213,  212,  211,  210,
      209,  208,  207,  206,  203,  202,  201,  200,  199,  198,
      197,  196,  195,  194,  193,  192,  190,  189,  188,  187,

      186,  185,  184,  183,  182,  181,  180,  179,  178,  177,
      176,  175,  174,  173,  172,  171,  170,  169,  168,  167,
      166,  165,  164,  163,  159,  158,  157,  156,  155,  154,
      153,  152,  151,  148,  147,  146,  145,  144,  143,  140,
      139,  138,  137,  136,  135,  134,  133,  132,  131,  130,
      129,  127,  126,  125,  124,  123,  120,  118,  117,  116,
      115,  114,  113,  109,  108,  107,  106,  105,  104,  103,
      102,  100,   99,   98,   97,   96,   94,   93,   91,   90,
       89,   87,   86,   85,   84,   83,   81,   79,   78,   77,
       76,   75,   74,   73,   72,   71,   70,   69,   68,   67,

       66,   65,   64,   63,   62,   61,   60,   59,   56,   55,
       54,   53,   52,   51,   50,   49,   48,   47,   45,   44,
       43,   42,   41,   40,   39,   38,   37,   36,   35,   33,
       28,   26,   25,   23,   22,   21,   20,   19,   17,   16,
       15,   14,   13,   12,    7,    6,    3,  556,  556,  556,
      556,  556,  556,  556,  556,  556,  556,  556,  556,  556,
      556,  556,  556,  556,  556,  556,  556,  556,  556,  556,
      556,  556,  556,  556,  556,  556,  556,  556,  556,  556,
      556,  556,  556,  556,  556,  556,  556,  556,  556,  556,
      556,  556,  556,  556,  556,  556,  556,  556,  556,  556,

      556,  556,  556
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#line 2 "lexer.l"
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "parser.h"
#line 805 "lexer.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

YYSTYPE * yyget_lval (void );

void yyset_lval (YYSTYPE * yylval_param  );

       YYLTYPE *yyget_lloc (void );
    
        void yyset_lloc (YYLTYPE * yylloc_param  );
    
/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex \
               (YYSTYPE * yylval_param,YYLTYPE * yylloc_param );

#define YY_DECL int yylex \
               (YYSTYPE * yylval_param, YYLTYPE * yylloc_param )
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
        YYSTYPE * yylval;
    
        YYLTYPE * yylloc;
    
#line 15 "lexer.l"

#line 1008 "lexer.c"

    yylval = yylval_param;

    yylloc = yylloc_param;

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 557 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 648 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 16 "lexer.l"
; 
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 18 "lexer.l"
return NODETYPE;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 19 "lexer.l"
return SOURCE;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 20 "lexer.l"
return SINK;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 21 "lexer.l"
return TRANSIT;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 23 "lexer.l"
return R_MARKOV;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 24 "lexer.l"
return R_UNF;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 25 "lexer.l"
return R_FILE;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 26 "lexer.l"
return R_OTHER;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 28 "lexer.l"
return ARRIVAL_TYPE;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 29 "lexer.l"
return ARRIVAL_LAMBDA;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 30 "lexer.l"
return ARRIVAL_FROM;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 31 "lexer.l"
return ARRIVAL_TO;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 32 "lexer.l"
return ARRIVAL_SAVETO;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 33 "lexer.l"
return ARRIVAL_LOADFROM;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 35 "lexer.l"
return QUEUE_MAXLENGTH;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 36 "lexer.l"
return QUEUE_SERVERS;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 37 "lexer.l"
return QUEUE_KIND;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 38 "lexer.l"
return FIFO_QUEUE;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 39 "lexer.l"
return SERVICE_TYPE;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 40 "lexer.l"
return SERVICE_LAMBDA;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 41 "lexer.l"
return SERVICE_TO;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 42 "lexer.l"
return SERVICE_FROM;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 43 "lexer.l"
return SERVICE_SAVETO;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 44 "lexer.l"
return SERVICE_LOADFROM;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 45 "lexer.l"
return DEPARTURE_SAVETO;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 47 "lexer.l"
return STOP_MAXTIME;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 48 "lexer.l"
return STOP_MAXARRIVAL;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 49 "lexer.l"
return STOP_QUEUEZERO;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 51 "lexer.l"
return CSMA_NSTATIONS;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 52 "lexer.l"
return CSMA_PROB;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 53 "lexer.l"
return CSMA_SLOTTIME;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 54 "lexer.l"
return CSMA_COLLISION;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 55 "lexer.l"
return CSMA_MAXBACKOFF;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 57 "lexer.l"
return PROTOCOL;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 58 "lexer.l"
return PROTO_ONE_QUEUE;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 59 "lexer.l"
return PROTO_CSMA;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 60 "lexer.l"
return PROTO_NET_QUEUE;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 61 "lexer.l"
return NTHREADS;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 63 "lexer.l"
return DEBUG_ERROR;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 64 "lexer.l"
return DEBUG_WARNING;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 65 "lexer.l"
return DEBUG_INFO;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 66 "lexer.l"
return LIBS_RANDOM;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 67 "lexer.l"
return LIB_RAND_IRAND;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 68 "lexer.l"
return LIB_RAND_RANDLIB;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 69 "lexer.l"
return EQ;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 70 "lexer.l"
return ENDLINE;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 71 "lexer.l"
return YES;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 72 "lexer.l"
return NO;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 73 "lexer.l"
{yylval->dval = atof(yytext); return REALNUM;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 74 "lexer.l"
{yylval->dval = atof(yytext); return REALNUM;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 75 "lexer.l"
{yylval->ival = atoi(yytext); return INTNUM;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 76 "lexer.l"
{yylval->ival = atoi(yytext); return INTNUM;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 77 "lexer.l"
{yylval->str = strdup(yytext); return STRING;}
	YY_BREAK
case 55:
/* rule 55 can match eol */
YY_RULE_SETUP
#line 80 "lexer.l"
;       /* ignore whitespace */ 
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 82 "lexer.l"
ECHO;
	YY_BREAK
#line 1377 "lexer.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 557 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 557 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 556);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 82 "lexer.l"


